/**
 * アイテム取得場所データ
 * 参考: Dead Rising Wiki (https://deadrising.fandom.com/), GameFAQs (jamby)
 */

const WIKI_BASE = "https://deadrising.fandom.com/wiki/";

/** アイテム名 → 取得場所一覧のマップ */
export const ITEM_LOCATIONS: Record<string, string[]> = {
  "2\" x 4\"": ["South Plaza", "Underground and Back Alleys"],
  "Acetylene Tank": ["Underground: South Plaza"],
  "Acoustic Guitar": ["Tune Makers (Royal Flush Plaza)", "Silver Strip (Stage Area)"],
  "Ad Board": ["Outside stores around the city"],
  "Amplifier": ["Tune Makers (Royal Flush Plaza)"],
  "Assault Rifle": ["Casino Security Offices and Vault Areas"],
  "Bag of Marbles": ["Ye Olde Toybox", "Children's Castle"],
  Barstool: ["Bars, Restaurants and Casinos"],
  "Baseball Bat": ["By the stairs on your way out of the vent room"],
  Basketball: ["Sportance", "KokoNutz Sports Town"],
  "Bass Guitar": ["Tune Makers", "Silver Strip (Stage Area)"],
  Battery: ["Maintenance Rooms (in the back of Tune Makers)"],
  "Battleaxe": ["Ned's Knicknackery (Palisades Mall 2nd Floor)"],
  Bench: ["In the arena back by the elevator you start the game at"],
  "Bingo Ball Cage": ["One Little Duck Bingo (Silver Strip)"],
  "Blast Frequency Gun": ["Secret Lab (Underground)"],
  "Bow and Arrow": ["The Chieftain's Hut (Royal Flush Plaza 1st Floor)"],
  "Bowie Knife": [
    "Bob's Fish 'n Hunt (P107) - Case Zero",
    "Still Creek Movie Theater (PR105) - Case Zero",
    "Americana Casino restroom / Bennie Jack's BBQ Shack (A101)",
    "Fortune Park - Maintenance Room 11 south side",
    "Palisades Mall - Ned's Knicknackery (P204) / Shanks (P107)",
    "Royal Flush Plaza first floor / rooftop / Yesterday, Today & Tomorrow (R114)",
    "Silver Strip - Luaii Wauwii (N105) on patio / Maintenance Room 16 behind Pub O' Gold (N107)",
    "Underground - Secret Lab",
  ],
  "Bowling Ball": ["Sportrance (Royal Flush Plaza 1st Floor)"],
  "Box of Nails": ["Maintenance Room as soon as you go up the stairs from the vent room"],
  "Boxing Gloves": ["The Man's Sport (Royal Flush Plaza 1st Floor)"],
  Brick: ["South Plaza", "Underground and Maintenance Halls"],
  Broadsword: ["Americana Casino (Hung on Walls)"],
  "Broom Handle": ["Broken off of Push Brooms"],
  Bucket: ["Room to the left as soon as you go up the stairs from the vent room"],
  "Bull Skull": ["Wild West Grill House"],
  "Cactus Plant": ["Food Court"],
  "Cardboard Box": ["All over the place", "Vent Room", "Safe House"],
  "Cardboard Cutout": ["Inside Paradise Platinum Screens (Platinum Strip)"],
  "Cash Register": ["Inside pretty much every shop"],
  "Casino Chips": ["Casinos (By Poker Tables)"],
  "Cement Saw": ["South Plaza"],
  "Centurion Bust": ["Atop slot machines in Yucatan Casino", "Modern Businessman in Royal Flush Plaza"],
  Chainsaw: ["South Plaza"],
  "Chef Knife": ["Antoine's (Royal Flush Plaza 2nd Floor)"],
  "Coffee Pot": ["Food Court (Inside Kitchens)"],
  "Comedy Trophy": ["Found during Hot Excitorama (Silver Strip) during \"Two's Company\" side mission"],
  "Computer Case": ["Security Offices and Vaults"],
  "Construction Hat": ["South Plaza"],
  "Cooking Oil": ["Food Court (Inside Kitchens)"],
  "Cooking Pot": ["Food Court (Inside Kitchens)"],
  "Croupier Stick": ["Found near Table Games in Casinos"],
  Crowbar: ["South Plaza"],
  "Cushioned Tall Chair": ["By slot machines in Casinos"],
  Dolly: ["South Plaza"],
  "Donkey Lamp": ["Arena's Green Room", "Diablo Mexican Restaurant (Food Court)"],
  "Drill Motor": ["South Plaza"],
  "Drink Cart": ["In Casinos"],
  Drum: ["Tune Makers"],
  Dumbbell: ["The Man's Sport (Royal Flush Plaza 1st Floor)"],
  Dynamite: [
    "Fortune City Arena - Maintenance Room 23",
    "Palisades Mall - Maintenance Room 9",
    "Royal Flush Plaza - outside Children's Castle atop palm tree",
    "Silver Strip - Maintenance Room 17",
    "Underground - Maintenance Room 33",
    "Food Court - Maintenance Room 5 / Wild West Grill House awning / upper platforms",
    "Fortune Park - main area / Maintenance Room 11",
    "Palisades Mall - first floor / second floor / Kid's Choice Clothing",
    "Silver Strip - Maintenance Room 14 / Rockets Red Glare on kiosk",
    "South Plaza - main floor / upper platforms",
    "Underground - Maintenance Room 31",
    "Uranus Zone - main area / south & west upper platforms / Maintenance Room 3 (OTR)",
    "Holding Pens / Living Quarters / Research Laboratory (Case West)",
  ],
  "Electric Guitar": ["Tune Makers"],
  "Fancy Bench": ["Around the Malls (Royal Flush Plaza)"],
  "Fancy Painting": ["The Cleroux Collection (Palisades Mall 2nd Floor)"],
  "Fancy Small Chair": ["In fine stores (Clothing and Jewelry)", "Slot Ranch Casino (Bibi's show stage)"],
  "Fancy Tall Chair": ["In fine stores (Clothing and Jewelry Stores)"],
  "Fire Axe": ["In the Arena by the Green Room", "Maintenance Halls"],
  "Fire Extinguisher": ["Right before you enter Royal Flush Plaza coming from the safe house"],
  Firecrackers: ["Astonishing Illusions (Royal Flush Plaza 1st Floor)"],
  Flashlight: ["Found in Offices", "Dropped by looters"],
  "Flower Pot": ["Venus Touch (Palisades Mall 1st Floor)"],
  "Foam Hand": ["Found on the ground at the Arena"],
  "Folding Chair": ["South Plaza"],
  Football: ["Sportrance (Royal Flush Plaza 1st Floor)"],
  "Fountain Firework": ["Astonishing Illusions (Royal Flush Plaza 1st Floor)"],
  "Funny Painting": ["The Cleroux Collection during \"Art Appreciation\""],
  "Garbage Bag": ["South Plaza"],
  "Gas Barrel": ["Found in Safe House during Case 6-4"],
  "Gasoline Canister": ["Yucatan Casino (Upper Platforms)", "South Plaza"],
  Gems: ["Marriage Makers (Royal Flush Plaza 1st Floor)"],
  Generator: ["Found in Safe House during Case 6-4"],
  "Giant Die": ["Royal Flush Plaza 1st Floor \"Flaming Craps\" table"],
  "Giant Pink Chainsaw": ["Found after defeating Randy in \"Here Comes The Groom\""],
  "Giant Stuffed Bull": ["Children's Castle (Royal Flush Plaza 2nd Floor)"],
  "Giant Stuffed Donkey": ["Small Fry Duds (Royal Flush Plaza 2nd Floor)"],
  "Giant Stuffed Elephant": ["Stylin' Toddlers (Royal Flush Plaza 1st Floor)"],
  "Giant Stuffed Rabbit": ["Americana Casino (Upper Platforms)", "Royal Flush Plaza 2nd Floor upper platforms"],
  "Gift Shop Lamp": ["Astonishing Illusions (Royal Flush Plaza 1st Floor)"],
  "Goblin Mask": ["Children's Castle (Royal Flush Plaza 2nd Floor)"],
  "Golf Club": ["Sportrance (Royal Flush Plaza 1st and 2nd Floor)"],
  Grenade: ["High-Noon Shooting Range (Palisades Mall 2nd Floor)"],
  "Gumball Machine": ["Children's Castle (Royal Flush Plaza 2nd Floor)"],
  Handbag: ["Found laying on the ground all over", "Women Stores (Royal Flush Plaza 1st and 2nd Floor)"],
  Handgun: ["High-Noon Shooting Range (Palisades Mall 2nd Floor)"],
  Hanger: ["Clothing Stores", "Sportrance (Royal Flush Plaza 2nd Floor)"],
  "Highback Oak Chair": ["Found all over (Royal Flush Plaza 1st Floor)"],
  "Hockey Stick": ["KokoNutz Sports Town (Palisades Mall 2nd Floor)"],
  "Hunk of Meat": ["Found by slaying Zombies", "Maintenance Room #11 at the south end of Fortune Park"],
  "Indoor Garbage Can": ["Found all over Royal Flush Plaza"],
  "Katana Sword": ["Found after killing psychopaths in Case 4-1"],
  Keg: ["Around Bars", "Food Court"],
  Ketchup: ["In most eateries", "Food Court"],
  Keyboard: ["Security Offices and Vault Areas"],
  Lamp: ["Found in most stores with a desk", "Fortune City Hotel"],
  Lance: ["Hamburger Fiefdom (Food Court)"],
  "Large Barrel": ["Found outside the Wild West Grill House (Food Court)"],
  "Large Fern Tree": ["Royal Flush Plaza: Near the Slot Ranch Casino entrance"],
  "Large Planter": ["Found all over the malls (Royal Flush Plaza, Palisades Mall)"],
  "Large Potted Plant": ["Found all over the malls (Royal Flush Plaza, Palisades Mall)"],
  "Large Vase": ["The Cleroux Collection (Palisades Mall 2nd Floor)"],
  "Large Wrench": ["South Plaza"],
  "Lawn Dart": ["In the grassy areas of Royal Flush Plaza"],
  "Lawn Mower": ["Fortune Park Maintenance Room #12 by the save point"],
  "LCD Monitor": ["Security Offices", "Modern stores"],
  "Lead Pipe": ["South Plaza"],
  "Leaf Blower": ["Slot Ranch Casino (Back Stage Area)"],
  "Leaf Rake": ["Grassy Areas in Fortune Park", "Maintenance Room #12 by the save point"],
  "Liberty Torch": ["Slot Ranch Casino's Stage"],
  "Lizard Mask": ["Americana Casino (Bennie Jack's BBQ Shack)"],
  LMG: ["Yucatan Casino (Atop \"Luck Marble\" Mini Game)"],
  "Long Stick": ["Fortune City Hotel (Vases of Bamboo in the lobby)"],
  Machete: ["Shank's (Palisades Mall 1st Floor)"],
  "Magician Sword": ["Found after defeating psychopaths during \"Deadliest Trick\" side mission"],
  Mailbox: ["Found along Silver and Platinum Strip"],
  "Mannequin Female": ["In most Clothing Stores", "Sportrance"],
  "Mannequin Male": ["In most Clothing Stores", "Sportrance"],
  Massager: ["Hot Excitorama (Silver Strip)"],
  Mayonnaise: ["Chris's Fine Foods (Palisades Mall 2nd Floor)"],
  "Meat Cleaver": ["Shank's (Palisades Mall 1st Floor)"],
  "Medicine Ball": ["Flexin' (Palisades Mall 1st Floor)"],
  "Merc Assault Rifle": ["Casino Security Offices", "Dropped by Mercenaries when killed"],
  "Metal Barricade": ["South Plaza"],
  "Metal Baseball Bat": ["The Man's Sport (Royal Flush Plaza 1st Floor)"],
  "Metal Garbage Can": ["Found all over"],
  "Mic Stand": ["Silver Strip (Stage Area)"],
  "Military Case": ["Underground", "Fortune City Hotel rooftop"],
  "Mining Pick": ["Wild West Grill House (Food Court)"],
  "MMA Gloves": ["The Man's Sport (Royal Flush Plaza 1st Floor)"],
  "Money Case": ["Fortune City Hotel rooftop"],
  Moosehead: ["Food Court (atop of information booth)"],
  "Motor Oil": ["Maintenance halls", "Underground"],
  "Music Discs": ["Players (Royal Flush Plaza 2nd Floor)"],
  Mustard: ["Food Court"],
  "Newspaper Box": ["Outside on the Silver Strip", "Inside (Royal Flush Plaza)"],
  Newspaper: ["Outside on the Silver Strip", "Inside (Royal Flush Plaza)"],
  Nightstick: ["Security Offices", "Dropped by zombie guards"],
  "Novelty Beer Mug": ["Juggz Bar & Grill (Platinum Strip)"],
  "Novelty Cell Phone": ["Rush Wireless (Royal Flush Plaza 2nd Floor)"],
  "Novelty Liquor Bottle": ["Leigh's Fine Liquor (Palisades Mall 2nd Floor)"],
  "Novelty Poker Chip": ["Barrel of Goods (Silver Strip)"],
  "Padded Blue Chair": ["Atlantica Casino (Magic Stage Area)"],
  Paddle: ["Palisades Mall (Central Grotto)"],
  "Paint Can": ["Hat store as soon as you come out of the safe house doors"],
  Painting: ["The Cleroux Collection (Palisades Mall 2nd Floor)"],
  Pallet: ["South Plaza", "Back alleys and rooftops"],
  Pan: ["Food Court (in kitchens)"],
  Parasol: ["Found atop Palisades Mall's Central Grotto"],
  "Patio Chair": ["Food Court (Restaurant Patios)"],
  "Patio Table": ["Food Court (Restaurant Patios)"],
  "Peace Art": ["The Cleroux Collection (Palisades Mall 2nd Floor)"],
  Pitchfork: ["Wild West Grill House (Food Court)"],
  "Plastic Bin": ["Back alleys on the Silver Strip"],
  "Plastic Garbage Can": ["Back alleys on the Silver Strip"],
  Plates: ["Food Court (in the kitchens)"],
  "Playing Cards": ["Casinos near the table games"],
  Plywood: ["Rooftops", "South Plaza", "Underground"],
  "Power Drill": ["Maintenance Room #3 right next to Sturdy Package (Royal Flush Plaza 1st Floor)"],
  "Propane Tank": ["First door to the left coming out of the vent room, laying on the floor to the right"],
  "Protestor Sign": ["Platinum Strip near TIR souvenir Kiosks by the entrance to The Arena"],
  "Push Broom": ["Maintenance Room #7 right next to Flexin' (Palisades Mall 1st Floor)"],
  Pylon: ["Found all over", "South Plaza"],
  Queen: ["Dropped by zombies flailing their arms in the air"],
  Nectar: ["Restaurants", "Bars"],
  "Robot Bear": ["Astonishing Illusions (Royal Flush Plaza 1st Floor)"],
  "Rocket Fireworks": ["Rockets Red Glare (Silver Strip)"],
  "Rocket Launcher": ["Found after defeating psychopaths during \"World's Most Deadliest Trick\" side mission"],
  "Rotating Display": ["Roy's Mart (Royal Flush Plaza 1st Floor)"],
  "Roulette Wheel": ["Near table games in the casinos"],
  "Round Potted Plant": ["Found all over, mostly grassy areas in Royal Flush Plaza"],
  "Sandwich Board": ["Mostly outside of shops in the food court"],
  "Saw Blade": ["South Plaza"],
  Scissors: ["Safe House (Security Room)"],
  "Servbot Mask": ["Ultimate Playhouse (Palisades Mall 1st Floor)"],
  "Serving Tray": ["Food Court (Kitchen Area)"],
  Shampoo: ["Wave Of Style (Royal Flush Plaza 2nd Floor)"],
  "Shopping Boxes": ["Kathy's Space (Royal Flush Plaza 2nd Floor)"],
  "Shopping Valuables": ["Only during \"Shopping Spree\" side mission in Kathy's Space"],
  Shotgun: ["High-Noon Shooting Range (Palisades Mall 2nd Floor)"],
  "Shower Head": ["Safe House near restroom"],
  "Six Shooter": ["Found after defeating psychopath Seymour during \"WWJWD\"", "Laying on table"],
  Skateboard: ["In The Closet (Royal Flush Plaza 1st Floor)"],
  "Sledge Hammer": ["Laying on the floor as soon as you come up the stairs from the vent room"],
  "Small Fern Tree": ["Found all over near door exits"],
  "Small Painting": ["The Cleroux Collection (Palisades Mall 2nd Floor)"],
  "Small Potted Plant": ["Found all over near door exits", "Roy's Mart on the counter"],
  "Small Suitcase": ["The Sturdy Package (Royal Flush Plaza 1st Floor)"],
  "Small Vase": ["The Cleroux Collection (Palisades Mall 2nd Floor)"],
  "Sniper Rifle": ["High-Noon Shooting Range (Palisades Mall 2nd Floor)"],
  "Soccer Ball": ["KokoNutz Sports Town (Palisades Mall 2nd Floor)"],
  Speaker: ["Tune Makers (Royal Flush Plaza 1st Floor)"],
  Spear: ["Ned's Knicknackery (Palisades Mall 2nd Floor)"],
  "Spool of Wire": ["Safe House during Case 6-4"],
  "Spot Light": ["Grassy Areas along Platinum Strip"],
  "Spray Paint": ["In The Closet (Royal Flush Plaza 1st Floor)"],
  "Square Sign": ["Found all over the place"],
  Stand: ["Found in casinos", "Fortune Hotel Lobby"],
  "Steel Shelving": ["Underground", "South Plaza"],
  "Step Ladder": ["Underground", "South Plaza", "Roof of Hamburger Fiefdom (via snack machines to the left)"],
  "Stick Pony": ["Ye Olde Toybox (Royal Flush Plaza 1st Floor)"],
  "Stone Statue": ["Found all over Yucatan Casino"],
  Stool: ["Common around Bars"],
  Suitcase: ["The Sturdy Package (Royal Flush Plaza 1st Floor)"],
  Swordfish: ["Luaii Wauwii (Silver Strip)"],
  "Table Lamp": ["Fortune City Hotel (on the Front Desk)"],
  "Tennis Racquet": ["KokoNutz Sports Town (Palisades Mall 1st Floor)"],
  "Tiki Mask": ["Luaii Wauwii (Silver Strip)"],
  "Tiki Torch": ["Found all over the Yucatan Casino"],
  Tire: ["Underground", "Leon's trailer"],
  Tomahawk: ["The Chieftain's Hut (Royal Flush Plaza 1st Floor)"],
  "Toy Helicopter": ["Ye Olde Toybox (Royal Flush Plaza 1st Floor)"],
  "Toy Spitball Gun": ["Ye Olde Toybox (Royal Flush Plaza 1st Floor)"],
  "Training Sword": ["Slot Ranch Casino (back stage area)"],
  "Treasure Chest": ["Atlantica Casino (all over main Floor)"],
  "Utility Cart": ["Found outside of One Little Duck Bingo (Silver Strip)"],
  "Vacuum Cleaner": ["Yucatan Casino's South VIP room", "Shoal Nightclub behind cash register"],
  "Velvet Bar": ["Fortune City Hotel's main lobby"],
  "Vinyl Records": ["Entertainment Isle (Palisades Mall 1st Floor)"],
  "Wacky Hammer": ["Moe's Maginations (Platinum Strip)"],
  "Water Bottle": ["Found by destroying water coolers"],
  "Water Cooler": ["In offices", "Safe House"],
  "Water Gun": ["Ultimate Playhouse (Palisades Mall 1st Floor)"],
  Wheelchair: ["Tune Makers (Royal Flush Plaza 1st Floor)"],
  "Whipped Cream": ["Palisades Mall's Central Grotto"],
  "Yellow Tall Chair": ["Near slot machines in Casinos"],
  "Zombie Mask": ["Stylin' Toddlers (Royal Flush Plaza 1st Floor)"],

  Sickle: ["Americana Casino - The American Historium"],
  Katana: ["Found after killing psychopaths in Case 4-1"],

  // === Case West 専用 ===
  "Impact Hammer": ["Research Laboratory (Case West)"],
  "Electric Prod": ["Research Laboratory (Case West)"],
  Defibrillator: ["Medical areas, hospital (Case West)"],
  "Medical Tray": ["Medical areas (Case West)"],
  "Syringe Gun": ["Research Laboratory (Case West)"],
  Chemicals: ["Research Laboratory (Case West)"],
  "Floor Buffer": ["Janitor areas (Case West)"],

  // === OTR 専用 ===
  Boomerang: ["Uranus Zone (OTR)"],
  "Alien Head": ["Uranus Zone (OTR)"],
  "Tennis Ball Launcher": ["Uranus Zone (OTR)"],
  "Grass Trimmer": ["Fortune Park (OTR)"],
  "Escape Pod": ["Uranus Zone (OTR)"],
};

/** アイテムのWikiページURLを取得 */
export function getItemWikiUrl(itemName: string): string {
  const base = itemName.split(" or ")[0].trim();
  const encoded = encodeURIComponent(base + "_(Dead_Rising_2)");
  return `${WIKI_BASE}${encoded}`;
}

/** アイテムの取得場所を取得（部分一致で検索） */
export function getItemLocations(itemName: string): string[] {
  const normalized = itemName.trim();
  if (!normalized) return [];

  // 完全一致を優先
  if (ITEM_LOCATIONS[normalized]) {
    return ITEM_LOCATIONS[normalized];
  }

  // "LMG or Merc Assault Rifle" 等の複合名 → 最初の部分で検索
  const firstPart = normalized.split(" or ")[0].trim();
  if (ITEM_LOCATIONS[firstPart]) {
    return ITEM_LOCATIONS[firstPart];
  }

  // 部分一致
  for (const [key, locations] of Object.entries(ITEM_LOCATIONS)) {
    if (
      normalized.toLowerCase().includes(key.toLowerCase()) ||
      firstPart.toLowerCase().includes(key.toLowerCase())
    ) {
      return locations;
    }
  }

  return [];
}
