/**
 * アイテム取得場所データ
 * 参考: Dead Rising Wiki (https://deadrising.fandom.com/), GameFAQs (jamby)
 */

const WIKI_BASE = "https://deadrising.fandom.com/wiki/";

// エリア名の定義（メンテナンス性を考慮）
const AREAS = {
  AMERICANA: "Americana Casino - Restroom Area",
  ATLANTICA: "Atlantica Casino - Rooftop",
  FOOD_COURT: "Food Court - Upper Platforms",
  FORTUNE_PARK: "Fortune Park - Maintenance Room 12",
  PLATINUM_STRIP: "Platinum Strip - Cinema Rooftop",
  SAFE_HOUSE: "Safe House",
  SILVER_STRIP: "Silver Strip - Main Area",
  SILVER_STRIP_MR19: "Silver Strip - Maintenance Room 19",
  SILVER_STRIP_TINKER: "Silver Strip - Tinkerbox (N103)",
  SOUTH_PLAZA: "South Plaza - Main Floor/Upper Platforms",
  UNDERGROUND: "Underground - Secret Lab/Warehouse A, B, E"
} as const;

/** アイテム名 → 取得場所一覧のマップ */
export const ITEM_LOCATIONS: Record<string, string[]> = {
  "2\" x 4\"": [
    "Americana Casino restroom area",
    "Atlantica Casino rooftop",
    "Food Court upper platforms",
    "Fortune Park - Maintenance Room 12",
    "Platinum Strip cinema rooftop",
    "Safe House",
    "Silver Strip main area",
    "Silver Strip - Maintenance Room 19",
    "Silver Strip - Tinkerbox (N103)",
    "South Plaza main floor/upper platforms",
    "Underground - Secret Lab/Warehouse A/Warehouse B/Warehouse E",
  ],
  "Acetylene Tank": ["Underground: South Plaza"],
  "Acoustic Guitar": ["Tune Makers (Royal Flush Plaza)", "Silver Strip (Stage Area)"],
  "Ad Board": ["Outside stores around the city"],
  "Amplifier": [
    "Entertainment Isle",
    "Robsaka Digital",
    "Tunemakers",
    "Silver Strip",
    "Underground",
  ],
  "Assault Rifle": [
    "Hungry Joe's Pizzeria - awning",
    "Platinum Strip - Moe's Maginations (S105)",
    "Royal Flush Plaza - Just in Time Payday Loans (R205)",
    "Underground - Warehouse B / Warehouse D",
    "Yucatan Casino cashier and vault area",
  ],
  "Bag of Marbles": ["Ye Olde Toybox", "Children's Castle"],
  Barstool: ["Bars, Restaurants and Casinos"],
  "Baseball Bat": [
    "Brockett Gas Station",
    "Flexin'",
    "Platinum Strip",
    "Royal Flush Plaza",
    "SporTrance",
    "Barrel of Goods",
    "South Plaza",
    "Tape It or Die Set",
    "Underground",
    "Uranus Zone",
  ],
  Basketball: ["Sportance", "KokoNutz Sports Town"],
  "Bass Guitar": ["Tune Makers", "Silver Strip (Stage Area)"],
  "Battery": [
    "Still Creek",
    "Americana Casino",
    "Fortune Park",
    "Royal Flush Plaza",
    "Silver Strip",
    "Slot Ranch Casino",
    "Underground",
    "Yucatan Casino",
    "Uranus Zone",
  ],
  "Battleaxe": ["Ned's Knicknackery (Palisades Mall 2nd Floor)"],
  Bench: ["In the arena back by the elevator you start the game at"],
  "Bingo Ball Cage": ["One Little Duck Bingo (Silver Strip)"],
  "Blast Frequency Gun": [
    "Underground main tunnel",
    "Underground - Secret Lab",
  ],
  "Beer": [
    "Americana Casino",
    "Bennie Jack's BBQ Shack (A101)",
    "Shots & Awe (A102)",
    "Atlantica Casino",
    "Sipparellos (T101)",
    "Wild West Grill House (F101)",
    "Fortune City Hotel",
    "Platinum Strip",
    "Eternal Timepieces (R206)",
    "Silver Strip",
    "Luaii Wauwii (N105)",
    "Pub O' Gold (N107)",
    "Shamrock Casino (N106)",
    "Juggz Bar & Grill (S103)",
    "Slot Ranch Casino",
    "South Plaza",
    "Underground",
    "Yucatan Casino",
    "Baron Von Brathaus (Y101)",
    "Uranus Zone",
    "Uranus Zone - Jump Space 7",
    "Uranus Zone - Space",
  ],
  "Bow and Arrow": [
    "Bob's Fish 'n Hunt",
    "The Chieftain's Hut",
    "Food Court",
    "Shanks",
    "Underground",
  ],
  "Bowie Knife": [
    "Bob's Fish 'n Hunt (P107) - Case Zero",
    "Still Creek Movie Theater (PR105) - Case Zero",
    "Americana Casino restroom / Bennie Jack's BBQ Shack (A101)",
    "Fortune Park - Maintenance Room 11 south side",
    "Palisades Mall - Ned's Knicknackery (P204) / Shanks (P107)",
    "Royal Flush Plaza first floor / rooftop / Yesterday, Today & Tomorrow (R114)",
    "Silver Strip - Luaii Wauwii (N105) on patio / Maintenance Room 16 behind Pub O' Gold (N107)",
    "Underground - Secret Lab",
  ],
  "Bowling Ball": ["Sportrance (Royal Flush Plaza 1st Floor)"],
  "Box of Nails": [
    "Atlantica Casino magic stage",
    "Atlantica Casino rooftop",
    "Atlantica Casino upper platforms",
    "Atlantica Casino - Maintenance Room 10",
    "Palisades Mall second floor main area",
    "Platinum Strip cinema rooftop",
    "Platinum Strip - Maintenance Room 20",
    "Royal Flush Plaza northwest maintenance area",
    "Royal Flush Plaza - Maintenance Room 1",
    "Royal Flush Plaza - Sturdy Package (R119)",
    "Silver Strip - Maintenance Room 15",
    "Silver Strip - Maintenance Room 19",
    "South Plaza main floor",
    "South Plaza - Maintenance Room 24",
    "Underground - Maintenance Room 32",
    "Underground - Secret Lab",
    "Underground - Warehouse A",
    "Underground - Warehouse B",
    "Underground - Warehouse E",
    "Yucatan Casino - Maintenance Room 6",
  ],
  "Boxing Gloves": [
    "The Man's Sport",
    "Bennie Jack's BBQ Shack",
    "Flexin'",
    "Fortune Park",
    "Silver Strip",
    "Barrel of Goods",
  ],
  Brick: ["South Plaza", "Underground and Maintenance Halls"],
  Broadsword: ["Americana Casino (Hung on Walls)"],
  "Broom Handle": ["Broken off of Push Brooms"],
  "Bucket": [
    "Americana Casino - Bennie Jack's BBQ Shack (A101)",
    "Food Court central platform and information booth",
    "Palisades Mall - Flexin' (P104)",
    "Palisades Mall - Chris' Fine Foods (P216)",
    "Platinum Strip main area",
    "Platinum Strip - Maintenance Room 21",
    "Royal Flush Plaza first floor main area",
    "Royal Flush Plaza northwest maintenance area",
    "Royal Flush Plaza southeast maintenance area",
    "Royal Flush Plaza - Maintenance Room 23",
    "Safe House",
    "Silver Strip maintenance hall",
    "Slot Ranch Casino bar area",
    "South Plaza main floor",
    "South Plaza upper platforms",
    "South Plaza - Maintenance Room 26",
    "Underground main tunnel",
    "Underground - Secret Lab",
  ],
  "Bull Skull": [
    "Food Court - Wild West Grill House (F101), on porch",
  ],
  "Cactus Plant": ["Food Court"],
  "Cardboard Box": ["All over the place", "Vent Room", "Safe House"],
  "Cardboard Cutout": ["Inside Paradise Platinum Screens (Platinum Strip)"],
  "Cash Register": ["Inside pretty much every shop"],
  "Casino Chips": ["Casinos (By Poker Tables)"],
  "Cement Saw": [
    "Silver Strip alley",
    "Silver Strip - Maintenance Room 19",
    "South Plaza main floor",
    "South Plaza upper platforms",
    "South Plaza - Maintenance Room 24",
    "Underground - Warehouse A",
    "Underground - Maintenance Room 30",
    "Underground - Maintenance Room 35",
  ],
  "Centurion Bust": ["Atop slot machines in Yucatan Casino", "Modern Businessman in Royal Flush Plaza"],
  Chainsaw: ["South Plaza"],
  "Chef Knife": ["Antoine's (Royal Flush Plaza 2nd Floor)"],
  "Coffee Pot": ["Food Court (Inside Kitchens)"],
  "Comedy Trophy": ["Found during Hot Excitorama (Silver Strip) during \"Two's Company\" side mission"],
  "Computer Case": [
    "Americana Casino",
    "Atlantica Casino",
    "Fortune City Arena",
    "Fortune City Hotel lobby",
    "Palisades Mall - Beach Body Swim House (P105)",
    "Palisades Mall - Wallington's (P106)",
    "Palisades Mall - Under the Sea Travels (P207)",
    "Palisades Mall - Severed Ties (P212)",
    "Royal Flush Plaza - Roy's Mart (R109)",
    "Royal Flush Plaza - Hat Racks (R115)",
    "Royal Flush Plaza - Wily Travels (P202)",
    "Royal Flush Plaza - Rush Wireless (R211)",
    "Underground - Secret Lab",
    "Yucatan Casino",
  ],
  "Construction Hat": [
    "Americana Casino cashier and vault area",
    "Atlantica Casino rooftop",
    "Atlantica Casino - Maintenance Room 10",
    "Fortune Park main area",
    "South Plaza main floor",
    "South Plaza upper platforms",
    "Underground main tunnel",
    "Underground - Secret Lab",
    "Underground - Warehouse A",
    "Underground - Warehouse B",
    "Underground - Warehouse E",
    "Underground - Maintenance Room 31",
    "Yucatan Casino cashier and vault area",
    "Yucatan Casino fireplace area",
    "Yucatan Casino main floor",
    "Yucatan Casino upper platforms",
    "Yucatan Casino - Maintenance Room 34",
    "Uranus Zone - ledge next to Space (U112)",
  ],
  "Cooking Oil": ["Food Court (Inside Kitchens)"],
  "Cooking Pot": ["Food Court (Inside Kitchens)"],
  "Croupier Stick": ["Found near Table Games in Casinos"],
  Crowbar: ["South Plaza"],
  "Cushioned Tall Chair": ["By slot machines in Casinos"],
  Dolly: ["South Plaza"],
  "Donkey Lamp": ["Arena's Green Room", "Diablo Mexican Restaurant (Food Court)"],
  "Drill Motor": [
    "Americana Casino cashier and vault area",
    "Food Court upper platforms",
    "Palisades Mall first floor main area",
    "Slot Ranch Casino cashier and vault area",
    "South Plaza - Maintenance Room 26",
    "Underground - Maintenance Room 35",
    "Yucatan Casino cashier and vault area",
  ],
  "Drink Cart": ["In Casinos"],
  Drum: ["Tune Makers"],
  Dumbbell: ["The Man's Sport (Royal Flush Plaza 1st Floor)"],
  "Dynamite": [
    "Fortune City Arena - Maintenance Room 23",
    "Palisades Mall - Maintenance Room 9",
    "Royal Flush Plaza - outside of Children's Castle, atop the palm tree",
    "Silver Strip - Maintenance Room 17",
    "Underground - Maintenance Room 33",
    "Fortune City Arena security area",
    "South Plaza - Maintenance Room 24",
    "South Plaza - Maintenance Room 27",
    "Underground - Maintenance Room 32",
    "Uranus Zone main area",
    "Uranus Zone south upper platforms",
    "Uranus Zone west upper platforms",
    "Uranus Zone - Maintenance Room 3",
    "Food Court - Maintenance Room 5 (Only during Case 2-2 / Case 3-2 in OTR)",
    "Food Court - Wild West Grill House, on awning (Only during Case 2-2 / Case 3-2 in OTR)",
    "Food Court upper platforms (Only during Case 2-2 / Case 3-2 in OTR)",
    "Fortune Park main area (Only during Case 2-2 / Case 3-2 in OTR)",
    "Fortune Park - Maintenance Room 11 (Only during Case 2-2 / Case 3-2 in OTR)",
    "Palisades Mall first floor main area, next to Underground access (Only during Case 2-2 / Case 3-2 in OTR)",
    "Palisades Mall second floor main area (Only during Case 2-2 / Case 3-2 in OTR)",
    "Palisades Mall - Kid's Choice Clothing (Only during Case 2-2 / Case 3-2 in OTR)",
    "Silver Strip - Maintenance Room 14 (Only during Case 2-2 / Case 3-2 in OTR)",
    "Silver Strip - Rockets Red Glare, on top of kiosk (Only during Case 2-2 / Case 3-2 in OTR)",
    "South Plaza main floor (Only during Case 2-2 / Case 3-2 in OTR)",
    "South Plaza upper platforms (Only during Case 2-2 / Case 3-2 in OTR)",
    "Underground - Maintenance Room 31 (Only during Case 2-2 / Case 3-2 in OTR)",
  ],
  "Electric Guitar": ["Tune Makers"],
  "Fancy Bench": ["Around the Malls (Royal Flush Plaza)"],
  "Fancy Painting": ["The Cleroux Collection (Palisades Mall 2nd Floor)"],
  "Fancy Small Chair": ["In fine stores (Clothing and Jewelry)", "Slot Ranch Casino (Bibi's show stage)"],
  "Fancy Tall Chair": ["In fine stores (Clothing and Jewelry Stores)"],
  "Fire Axe": [
    "Fortune City Arena green rooms",
    "Fortune City Arena main floor",
    "Safe House",
    "South Plaza main floor",
    "Underground - Maintenance Room 30",
    "Underground - Secret Lab",
    "Underground - Warehouse B",
    "Underground - Warehouse C",
    "Underground - Warehouse E",
    "Yucatan Casino - Maintenance Room 6",
    "Yucatan Casino - Shoal Nightclub",
  ],
  "Fire Extinguisher": [
    "Americana Casino security office",
    "Atlantica Casino security office",
    "Food Court - Hamburger Fiefdom (F105)",
    "Fortune City Arena green rooms",
    "Fortune City Arena - Maintenance Room 23",
    "Fortune Park - Maintenance Room 13",
    "Palisades Mall - Maintenance Room 7",
    "Palisades Mall - Maintenance Room 9",
    "Palisades Mall - Under the Sea Travels (P207)",
    "Palisades Mall - The Cleroux Collection (P210)",
    "Platinum Strip - Paradise Platinum Screens (S104)",
    "Royal Flush Plaza northwest maintenance area",
    "Royal Flush Plaza - Casual Gals (R101)",
    "Royal Flush Plaza - Roy's Mart (R109)",
    "Royal Flush Plaza - Wily Travels (R202)",
    "Royal Flush Plaza - Antoine's (R203)",
    "Safe House",
    "Silver Strip maintenance hall",
    "Silver Strip - Maintenance Room 17",
    "Silver Strip - Rockets Red Glare (N108)",
    "Slot Ranch Casino cashier and vault area",
    "Yucatan Casino VIP room",
    "Yucatan Casino - Maintenance Room 6",
    "Yucatan Casino - Maintenance Room 34",
    "Yucatan Casino - Shoal Nightclub (Y102)",
  ],
  Firecrackers: ["Astonishing Illusions (Royal Flush Plaza 1st Floor)"],
  "Flashlight": [
    "Atlantica Casino magic stage",
    "Atlantica Casino main floor",
    "Atlantica Casino poker room",
    "Fortune City Arena green rooms",
    "Fortune City Arena main floor",
    "Fortune City Arena security area",
    "Fortune City Hotel rooftop",
    "Palisades Mall - Maintenance Room 8",
    "Palisades Mall - Ned's Knicknackery",
    "Platinum Strip north upper platforms",
    "Royal Flush Plaza first floor main area",
    "Silver Strip main area",
    "Silver Strip - Maintenance Room 16",
    "Silver Strip - One Little Duck Bingo",
    "Silver Strip - Tinkerbox",
    "Slot Ranch Casino cashier and vault area",
    "Slot Ranch Casino main floor",
    "Slot Ranch Casino - Maintenance Room 4",
    "Underground - Secret Lab",
    "Yucatan Casino fireplace area",
    "Yucatan Casino main floor",
    "Yucatan Casino upper platforms",
  ],
  "Flower Pot": ["Venus Touch (Palisades Mall 1st Floor)"],
  "Foam Hand": ["Found on the ground at the Arena"],
  "Folding Chair": ["South Plaza"],
  Football: ["Sportrance (Royal Flush Plaza 1st Floor)"],
  "Fountain Firework": [
    "The American Historium",
    "Rockets Red Glare",
    "Americana Casino",
    "Platinum Strip",
    "Astonishing Illusions",
  ],
  "Funny Painting": ["The Cleroux Collection during \"Art Appreciation\""],
  "Garbage Bag": ["South Plaza"],
  "Gas Barrel": ["Found in Safe House during Case 6-4"],
  "Gasoline Canister": [
    "Americana Casino - Shots & Awe (A102)",
    "Atlantica Casino upper platforms",
    "Palisades Mall - Chris' Fine Foods (P216)",
    "Silver Strip alley",
    "South Plaza main floor",
    "Underground - Warehouse B",
    "Underground - Warehouse C",
    "Underground - Warehouse E",
    "Yucatan Casino restroom area",
    "Yucatan Casino upper platforms",
    "Yucatan Casino - Baron Von Brathaus (Y101)",
    "Yucatan Casino - Maintenance Room 34",
  ],
  "Gems": [
    "Palisades Mall - Everything Diamond",
    "Palisades Mall - Ned's Knicknackery",
    "Platinum Strip north upper platforms",
    "Royal Flush Plaza - Albert's Apparel",
    "Royal Flush Plaza - Eternal Timepieces",
    "Royal Flush Plaza - Marriage Makers",
    "Royal Flush Plaza - Modern Businessman",
    "Silver Strip - Maintenance Room 16",
    "Silver Strip - One Little Duck Bingo",
    "Silver Strip - Pub O' Gold",
    "Slot Ranch Casino cashier and vault area",
    "Slot Ranch Casino main floor",
    "Slot Ranch Casino stage area",
    "Slot Ranch Casino - Maintenance Room 4",
  ],
  Generator: ["Found in Safe House during Case 6-4"],
  "Giant Die": ["Royal Flush Plaza 1st Floor \"Flaming Craps\" table"],
  "Giant Pink Chainsaw": ["Found after defeating Randy in \"Here Comes The Groom\""],
  "Giant Stuffed Bull": ["Children's Castle (Royal Flush Plaza 2nd Floor)"],
  "Giant Stuffed Donkey": ["Small Fry Duds (Royal Flush Plaza 2nd Floor)"],
  "Giant Stuffed Elephant": ["Stylin' Toddlers (Royal Flush Plaza 1st Floor)"],
  "Giant Stuffed Rabbit": ["Americana Casino (Upper Platforms)", "Royal Flush Plaza 2nd Floor upper platforms"],
  "Gift Shop Lamp": ["Astonishing Illusions (Royal Flush Plaza 1st Floor)"],
  "Goblin Mask": [
    "Royal Flush Plaza - Children's Castle",
    "Silver Strip - Maintenance Room 14",
  ],
  "Golf Club": ["Sportrance (Royal Flush Plaza 1st and 2nd Floor)"],
  Grenade: ["High-Noon Shooting Range (Palisades Mall 2nd Floor)", "P218 High-Noon Shooting Range"],
  "Gumball Machine": ["Children's Castle (Royal Flush Plaza 2nd Floor)"],
  Handbag: ["Found laying on the ground all over", "Women Stores (Royal Flush Plaza 1st and 2nd Floor)"],
  Handgun: ["High-Noon Shooting Range (Palisades Mall 2nd Floor)"],
  Hanger: ["Clothing Stores", "Sportrance (Royal Flush Plaza 2nd Floor)"],
  "Highback Oak Chair": ["Found all over (Royal Flush Plaza 1st Floor)"],
  "Hockey Stick": ["KokoNutz Sports Town (Palisades Mall 2nd Floor)"],
  "Hunk of Meat": ["Found by slaying Zombies", "Maintenance Room #11 at the south end of Fortune Park"],
  "Indoor Garbage Can": ["Found all over Royal Flush Plaza"],
  "Katana Sword": ["Found after killing psychopaths in Case 4-1"],
  Keg: ["Around Bars", "Food Court"],
  Ketchup: ["In most eateries", "Food Court"],
  Keyboard: ["Security Offices and Vault Areas"],
  Lamp: ["Found in most stores with a desk", "Fortune City Hotel"],
  Lance: ["Hamburger Fiefdom (Food Court)"],
  "Large Barrel": ["Found outside the Wild West Grill House (Food Court)"],
  "Large Fern Tree": ["Royal Flush Plaza: Near the Slot Ranch Casino entrance"],
  "Large Planter": ["Found all over the malls (Royal Flush Plaza, Palisades Mall)"],
  "Large Potted Plant": ["Found all over the malls (Royal Flush Plaza, Palisades Mall)"],
  "Large Vase": ["The Cleroux Collection (Palisades Mall 2nd Floor)"],
  "Large Wrench": ["South Plaza"],
  "Lawn Dart": [
    "Food Court - Maintenance Room 5",
    "Fortune Park central grotto",
    "Palisades Mall first floor main area",
    "Platinum Strip main area",
    "Royal Flush Plaza first floor main area",
  ],
  "Lawn Mower": [
    "Fortune Park central grotto",
    "Fortune Park - Maintenance Room 12",
    "Fortune Park - Maintenance Room 13",
    "Palisades Mall - Maintenance Room 9",
    "Platinum Strip - Maintenance Room 22",
    "Silver Strip - Luaii Wauwii (N105), on patio",
    "Yucatan Casino - Baron Von Brathaus (Y101)",
    "Yucatan Casino - Maintenance Room 34",
  ],
  "LCD Monitor": ["Security Offices", "Modern stores"],
  "Lead Pipe": ["South Plaza"],
  "Leaf Blower": [
    "Fortune Park main area",
    "Palisades Mall grotto",
    "Platinum Strip - Maintenance Room 21",
    "Slot Ranch Casino stage area",
    "Slot Ranch Casino - Maintenance Room 4",
    "Underground - Maintenance Room 31",
  ],
  "Leaf Rake": [
    "Fortune Park main area",
    "Fortune Park - Maintenance Room 12",
    "Royal Flush Plaza first floor main area",
    "Safe House rooftop",
    "Underground - Maintenance Room 31",
  ], "Liberty Torch": ["Slot Ranch Casino's Stage"],
  "Lizard Mask": [
    "Americana Casino - Bennie Jack's BBQ Shack (A101)",
    "Americana Casino - Maintenance Room 28",
    "Atlantica Casino magic stage",
    "Platinum Strip main area",
    "Platinum Strip - Moe's Maginations (S105)",
    "Royal Flush Plaza - Ye Olde Toybox (R107)",
    "Silver Strip - Luaii Wauwii (N105)",
  ],
  "LMG": [
    "Palisades Mall grotto - hidden in the brush [1] (Not in Off the Record)",
    "Palisades Mall - Army Surplus Gift Store for purchase (Not in Off the Record)",
    "Platinum Strip north upper platforms - Cash Gordon's Casino (atop) [2] (Not in Off the Record)",
    "Yucatan Casino - On top of the center pyramid [3] (Not in Off the Record)",
    "Yucatan Casino cashier and vault area - In the room leading to the vault (Case 3-2+) (Not in Off the Record)",
    "Royal Flush Plaza - Just in Time Payday Loans for purchase [Verification needed] (Not in Off the Record)",
    "Underground - Warehouse D (after Case 6-2: Last Stand)",
  ],
  "Long Stick": ["Fortune City Hotel (Vases of Bamboo in the lobby)"],
  "Machete": [
    "Atlantica Casino main floor, sticking out of a wall to the left of the Killer Blackjack machine",
    "Atlantica Casino upper platforms",
    "Food Court - Hungry Joe's Pizzeria (F107), on top of kitchen vents [note 1]",
    "Fortune City Arena - Maintenance Room 23",
    "Palisades Mall - Shanks (P107)",
    "Royal Flush Plaza - Albert's Apparel (R201)",
    "Silver Strip - Pub O' Gold (N107), on planter slightly to the right of the entrance",
    "Silver Strip - Maintenance Room 18",
    "Underground - Secret Lab",
    "Yucatan Casino fireplace area",
    "Yucatan Casino main entry area, on top of large statue",
    "Yucatan Casino - Baron Von Brathaus (Y101)",
  ],
  "Magician Sword": ["Found after defeating psychopaths during \"Deadliest Trick\" side mission"],
  Mailbox: ["Found along Silver and Platinum Strip"],
  "Mannequin Female": ["In most Clothing Stores", "Sportrance"],
  "Mannequin Male": ["In most Clothing Stores", "Sportrance"],
  Massager: ["Hot Excitorama (Silver Strip)"],
  Mayonnaise: ["Chris's Fine Foods (Palisades Mall 2nd Floor)"],
  "Meat Cleaver": ["Shank's (Palisades Mall 1st Floor)"],
  "Medicine Ball": ["Flexin' (Palisades Mall 1st Floor)"],
  "Merc Assault Rifle": [
    "Held by mercenaries",
    "Americana Casino cashier and vault area",
    "Atlantica Casino security office, lying on a table",
    "Slot Ranch Casino cashier and vault area",
    "Underground - Maintenance Room 29",
    "Yucatan Casino cashier and vault area",
  ],
  "Metal Barricade": ["South Plaza"],
  "Metal Baseball Bat": ["The Man's Sport (Royal Flush Plaza 1st Floor)"],
  "Metal Garbage Can": ["Found all over"],
  "Mic Stand": ["Silver Strip (Stage Area)"],
  "Military Case": ["Underground", "Fortune City Hotel rooftop"],
  "Mining Pick": ["Wild West Grill House (Food Court)"],
  "MMA Gloves": ["The Man's Sport (Royal Flush Plaza 1st Floor)"],
  "Money Case": ["Fortune City Hotel rooftop"],
  Moosehead: ["Food Court (atop of information booth)"],
  "Motor Oil": [
    "Food Court - Wild West Grill House (F101)",
    "Palisades Mall - Maintenance Room 8",
    "Slot Ranch Casino cashier and vault area",
    "Slot Ranch Casino - Maintenance Room 4",
    "Underground - Warehouse B",
  ],
  "Music Discs": ["Players (Royal Flush Plaza 2nd Floor)"],
  Mustard: ["Food Court"],
  "Newspaper Box": ["Outside on the Silver Strip", "Inside (Royal Flush Plaza)"],
  "Newspaper": [
    "Atlantica Casino magic stage",
    "Atlantica Casino main floor",
    "Atlantica Casino maintenance area",
    "Food Court - Maintenance Room 5",
    "Palisades Mall first floor main area",
    "Palisades Mall - Robsaka Digital",
    "Palisades Mall - Robsaka Mobile",
    "Palisades Mall - Stan's Large Print Books and Magazines",
    "Platinum Strip - Maintenance Room 22 South of TIR Souvenir Kiosk",
    "Royal Flush Plaza first floor main area",
    "Royal Flush Plaza - Rush Wireless",
    "Royal Flush Plaza - The Dark Bean",
    "Slot Ranch Casino bar area",
    "Slot Ranch Casino cashier and vault area",
  ],
  Nightstick: ["Security Offices", "Dropped by zombie guards"],
  "Novelty Beer Mug": ["Juggz Bar & Grill (Platinum Strip)"],
  "Novelty Cell Phone": ["Rush Wireless (Royal Flush Plaza 2nd Floor)"],
  "Novelty Liquor Bottle": ["Leigh's Fine Liquor (Palisades Mall 2nd Floor)"],
  "Novelty Poker Chip": ["Barrel of Goods (Silver Strip)"],
  "Padded Blue Chair": ["Atlantica Casino (Magic Stage Area)"],
  "Paddle": [
    "Palisades Mall grotto",
    "Palisades Mall - Under the Sea Travels",
    "Silver Strip - Luaii Wauwii",
    "Silver Strip - Maintenance Room 15",
    "South Plaza - Maintenance Room 25",
  ],
  "Paint Can": ["Hat store as soon as you come out of the safe house doors"],
  Painting: ["The Cleroux Collection (Palisades Mall 2nd Floor)"],
  Pallet: ["South Plaza", "Back alleys and rooftops"],
  Pan: ["Food Court (in kitchens)"],
  "Parasol": [
    "Food Court - Cucina Donnacci",
    "Palisades Mall grotto",
    "Palisades Mall - Under the Sea Travels",
    "Platinum Strip main area",
    "Platinum Strip - Maintenance Room 21",
    "Underground - Warehouse C",
    "Underground - Maintenance Room 31",
  ],
  "Patio Chair": ["Food Court (Restaurant Patios)"],
  "Patio Table": ["Food Court (Restaurant Patios)"],
  "Peace Art": ["The Cleroux Collection (Palisades Mall 2nd Floor)"],
  "Pitchfork": [
    "Food Court - Wild West Grill House (F101)",
    "Fortune Park central grotto",
    "Palisades Mall first floor main area",
    "South Plaza - Maintenance Room 26",
    "Underground main tunnel (on train) / Warehouse E",
    "Yucatan Casino fireplace area",
  ],
  "Plastic Bin": ["Back alleys on the Silver Strip"],
  "Plastic Garbage Can": ["Back alleys on the Silver Strip"],
  "Plates": [
    "Americana Casino - Bennie Jack's BBQ Shack",
    "Food Court - Cheesecake Mania",
    "Food Court - Cucina Donnacci",
    "Food Court - Rojo Diablo Mexican Restaurant",
    "Food Court - Wild West Grill House",
    "Platinum Strip - Dining at Davey's",
    "Royal Flush Plaza - Antoine's",
    "Silver Strip - Luaii Wauwii",
    "South Plaza main floor",
    "South Plaza upper platforms",
    "South Plaza - Maintenance Room 24",
    "Underground main tunnel",
    "Underground - Warehouse B",
    "Underground - Warehouse E",
    "Underground - Maintenance Room 35",
    "Yucatan Casino VIP room",
    "Yucatan Casino - Baron Von Brathaus",
  ],
  "Playing Cards": ["Casinos near the table games"],
  Plywood: ["Rooftops", "South Plaza", "Underground"],
  "Power Drill": ["Maintenance Room #3 right next to Sturdy Package (Royal Flush Plaza 1st Floor)"],
  "Propane Tank": [
    "Americana Casino cashier and vault area",
    "Platinum Strip - Maintenance Room 20",
    "Royal Flush Plaza northwest maintenance area",
    "Safe House",
    "Silver Strip - Maintenance Room 15",
    "Slot Ranch Casino cashier and vault area",
    "South Plaza main floor",
    "South Plaza - Maintenance Room 24",
    "Underground - Maintenance Room 32",
    "Yucatan Casino cashier and vault area",
    "Yucatan Casino - Maintenance Room 6",
  ],
  "Protestor Sign": ["Platinum Strip near TIR souvenir Kiosks by the entrance to The Arena"],
  "Push Broom": [
    "Americana Casino - Bennie Jack's BBQ Shack",
    "Atlantica Casino magic stage",
    "Atlantica Casino maintenance area",
    "Atlantica Casino poker room",
    "Atlantica Casino rooftop",
    "Atlantica Casino security office",
    "Atlantica Casino - Maintenance Room 10",
    "Food Court - Cheesecake Mania",
    "Food Court central platform and information booth",
    "Food Court upper platforms",
    "Fortune City Arena - Maintenance Room 23",
    "Palisades Mall - Maintenance Room 7",
    "Palisades Mall - Chris' Fine Foods (P216)",
    "Platinum Strip main area",
    "Royal Flush Plaza first floor main area",
    "Royal Flush Plaza northwest maintenance area",
    "Royal Flush Plaza southeast maintenance area",
    "Safe House",
    "Silver Strip Maintenance Room 18",
    "South Plaza main floor",
    "Underground - Maintenance Room 34",
    "Underground - Warehouse B",
    "Underground - Warehouse C",
    "Yucatan Casino - Maintenance Room 6",
  ],
  "Pylon": [
    "Americana Casino main floor",
    "Americana Casino restroom area",
    "Atlantica Casino rooftop",
    "Food Court - Maintenance Room 5",
    "Fortune City Arena main floor",
    "Fortune City Hotel rooftop",
    "Fortune Park - Maintenance Room 13",
    "Platinum Strip - Paradise Platinum Screens rooftop",
    "Royal Flush Plaza northwest maintenance area",
    "Royal Flush Plaza rooftop",
    "Safe House",
    "Safe House rooftop",
    "Silver Strip alley",
    "South Plaza main floor",
    "South Plaza upper platforms",
    "South Plaza Maintenance Room 27",
    "Underground main tunnel",
    "Underground - Secret Lab",
    "Underground - Warehouse A",
    "Underground - Warehouse C",
    "Underground - Warehouse E",
  ],
  Queen: ["Dropped by zombies flailing their arms in the air"],
  Nectar: ["Restaurants", "Bars"],
  "Robot Bear": [
    "Palisades Mall - Brand New U (P203)",
    "Platinum Strip - Moe's Maginations (S105)",
    "Royal Flush Plaza - Astonishing Illusions (R118)",
    "Platinum Strip south upper platforms",
  ],
  "Rocket Fireworks": ["Rockets Red Glare (Silver Strip)"],
  "Rocket Launcher": ["Found after defeating psychopaths during \"World's Most Deadliest Trick\" side mission"],
  "Rotating Display": ["Roy's Mart (Royal Flush Plaza 1st Floor)"],
  "Roulette Wheel": ["Near table games in the casinos"],
  "Round Potted Plant": ["Found all over, mostly grassy areas in Royal Flush Plaza"],
  "Sandwich Board": ["Mostly outside of shops in the food court"],
  "Saw Blade": [
    "Food Court upper platforms",
    "Royal Flush Plaza northwest maintenance area",
    "Silver Strip - Maintenance Room 19",
    "South Plaza main floor",
    "South Plaza - Maintenance Room 27",
    "Underground - Warehouse B",
    "Underground - Maintenance Room 30",
    "Yucatan Casino fireplace area",
    "Yucatan Casino upper platforms",
  ],
  Scissors: ["Safe House (Security Room)"],
  "Servbot Mask": [
    "Palisades Mall - Maintenance Room 9",
    "Palisades Mall - Ultimate Playhouse",
    "Silver Strip alley",
    "Underground main tunnel",
    "Underground - Maintenance Room 34",
    "Yucatan Casino - Baron Von Brathaus",
  ],
  "Serving Tray": ["Food Court (Kitchen Area)"],
  Shampoo: ["Wave Of Style (Royal Flush Plaza 2nd Floor)"],
  "Shopping Boxes": ["Kathy's Space (Royal Flush Plaza 2nd Floor)"],
  "Shopping Valuables": ["Only during \"Shopping Spree\" side mission in Kathy's Space"],
  "Shotgun": [
    "Palisades Mall - Severed Ties (P212) [note 1] / High-Noon Shooting Range (P218)",
    "Silver Strip stage area [note 2] / outside of Shamrock Casino [note 3]",
    "Underground main tunnel [note 4] / Maintenance Room 35",
    "Yucatan Casino - Shoal Nightclub (Y102) [note 5] / [note 6]",
    "South Plaza - American Undies [note 7]",
    "Fortune City Arena [note 8]",
    "Held by Andy Talbat",
    "Held by Chad Elchart",
    "Held by Carl Schliff [note 9]",
  ],
  "Shower Head": ["Safe House near restroom"],
  "Six Shooter": ["Found after defeating psychopath Seymour during \"WWJWD\"", "Laying on table"],
  Skateboard: ["In The Closet (Royal Flush Plaza 1st Floor)"],
  "Sledge Hammer": [
    "Americana Casino cashier and vault area",
    "Atlantica Casino rooftop",
    "Royal Flush Plaza northwest maintenance area",
    "South Plaza main floor",
    "Underground main tunnel",
    "Underground - Maintenance Room 30",
    "Underground - Secret Lab",
    "Underground - Warehouse B",
    "Underground - Warehouse C",
    "Underground - Warehouse E",
    "Yucatan Casino upper platforms",
    "Yucatan Casino - Maintenance Room 6",
  ],
  "Small Fern Tree": ["Found all over near door exits"],
  "Small Painting": ["The Cleroux Collection (Palisades Mall 2nd Floor)"],
  "Small Potted Plant": ["Found all over near door exits", "Roy's Mart on the counter"],
  "Small Suitcase": ["The Sturdy Package (Royal Flush Plaza 1st Floor)"],
  "Small Vase": ["The Cleroux Collection (Palisades Mall 2nd Floor)"],
  "Sniper Rifle": ["High-Noon Shooting Range (Palisades Mall 2nd Floor)"],
  "Soccer Ball": ["KokoNutz Sports Town (Palisades Mall 2nd Floor)"],
  Speaker: ["Tune Makers (Royal Flush Plaza 1st Floor)"],
  Spear: ["Ned's Knicknackery (Palisades Mall 2nd Floor)"],
  "Spool of Wire": ["Safe House during Case 6-4"],
  "Spot Light": ["Grassy Areas along Platinum Strip"],
  "Spray Paint": ["In The Closet (Royal Flush Plaza 1st Floor)"],
  "Square Sign": ["Found all over the place"],
  Stand: ["Found in casinos", "Fortune Hotel Lobby"],
  "Steel Shelving": ["Underground", "South Plaza"],
  "Step Ladder": ["Underground", "South Plaza", "Roof of Hamburger Fiefdom (via snack machines to the left)"],
  "Stick Pony": ["Ye Olde Toybox (Royal Flush Plaza 1st Floor)"],
  "Stone Statue": ["Found all over Yucatan Casino"],
  Stool: ["Common around Bars"],
  Suitcase: ["The Sturdy Package (Royal Flush Plaza 1st Floor)"],
  Swordfish: ["Luaii Wauwii (Silver Strip)"],
  "Table Lamp": ["Fortune City Hotel (on the Front Desk)"],
  "Tennis Racquet": [
    "Palisades Mall first floor main area, on red couch to the left of Wallington's (P106)",
    "Yucatan Casino VIP room / Baron Von Brathaus (Y101) (on grassy ledge hidden in the plants)",
  ],
  "Tiki Mask": ["Luaii Wauwii (Silver Strip)"],
  "Tiki Torch": [
    "Food Court - Wild West Grill House (F101)",
    "Palisades Mall grotto",
    "Yucatan Casino fireplace area",
    "Yucatan Casino main entry area",
    "Yucatan Casino main floor",
  ],
  Tire: ["Underground", "Leon's trailer"],
  Tomahawk: ["The Chieftain's Hut (Royal Flush Plaza 1st Floor)"],
  "Toy Helicopter": [
    "Palisades Mall - Ultimate Playhouse (P103)",
    "Royal Flush Plaza rooftop",
    "Royal Flush Plaza - Children's Castle (R209)",
    "Royal Flush Plaza - Ye Olde Toybox (R107)",
    "Silver Strip stage area",
    "Yucatan Casino - Baron Von Brathaus (Y101)",
  ],
  "Toy Spitball Gun": [
    "Palisades Mall - Ultimate Playhouse (P103)",
    "Royal Flush Plaza - Ye Olde Toybox (R107)",
    "Yucatan Casino - Baron Von Brathaus (Y101)",
    "Yucatan Casino - Maintenance Room 6",
  ],
  "Training Sword": [
    "Atlantica Casino main floor",
    "Atlantica Casino upper platforms",
    "Atlantica Casino - Maintenance Room 10",
    "Slot Ranch Casino stage area",
    "Slot Ranch Casino - Maintenance Room 4",
    "Food Court - Hamburger Fiefdom",
  ],
  "Treasure Chest": ["Atlantica Casino (all over main Floor)"],
  "Utility Cart": ["Found outside of One Little Duck Bingo (Silver Strip)"],
  "Vacuum Cleaner": [
    "Americana Casino security office",
    "Safe House",
    "South Plaza main floor",
    "South Plaza - Maintenance Room 27",
    "Underground - Warehouse B",
    "Yucatan Casino VIP room",
    "Yucatan Casino - Shoal Nightclub (Y102)",
  ],
  "Velvet Bar": ["Fortune City Hotel's main lobby"],
  "Vinyl Records": ["Entertainment Isle (Palisades Mall 1st Floor)"],
  "Wacky Hammer": ["Moe's Maginations (Platinum Strip)"],
  "Water Bottle": ["Found by destroying water coolers"],
  "Water Cooler": ["In offices", "Safe House"],
  "Water Gun": [
    "Atlantica Casino main floor",
    "Atlantica Casino security office",
    "Atlantica Casino upper platforms",
    "Fortune Park central grotto",
    "Fortune Park main area",
    "Palisades Mall grotto",
    "Palisades Mall - Maintenance Room 7",
    "Palisades Mall - Chris' Fine Foods (P216)",
    "Palisades Mall - Kid's Choice Clothing (P209)",
    "Palisades Mall - Ultimate Playhouse (P103)",
    "Platinum Strip - Moe's Maginations (S105)",
    "Silver Strip - Barrel of Goods (N104)",
    "South Plaza main floor",
    "South Plaza upper platforms",
    "Underground - Warehouse B",
    "Yucatan Casino main floor",
    "Yucatan Casino upper platforms",
    "Yucatan Casino - Maintenance Room 34",
    "Yucatan Casino - Shoal Nightclub (Y102)",
  ],
  "Wheelchair": [
    "Americana Casino main floor",
    "Americana Casino - Maintenance Room 28",
    "Fortune City Hotel lobby",
    "Platinum Strip - Cash Gordon's Casino (S102)",
    "Platinum Strip - Maintenance Room 22",
    "Royal Flush Plaza first floor main area",
    "Royal Flush Plaza - Maintenance Room 2",
    "Royal Flush Plaza - Tunemakers (R105)",
    "Slot Ranch Casino main floor",
    "Underground - Warehouse A",
    "Underground - Maintenance Room 29",
    "Underground - Maintenance Room 31",
    "Yucatan Casino main floor",
  ],
  "Whiskey": [
    "Americana Casino main floor",
    "Americana Casino - Bennie Jack's BBQ Shack",
    "Atlantica Casino magic stage",
    "Atlantica Casino main floor",
    "Atlantica Casino poker room",
    "Atlantica Casino rooftop",
    "Atlantica Casino - Sipparellos (T101)",
    "Food Court - Maintenance Room 5",
    "Food Court main floor",
    "Food Court - Cheesecake Mania",
    "Palisades Mall - Kicks for Her",
    "Palisades Mall - Leigh's Fine Liquor",
    "Palisades Mall - Wallington's",
    "Platinum Strip - Juggz Bar & Grill",
    "Platinum Strip - Maintenance Room 22",
    "Royal Flush Plaza rooftop",
    "Silver Strip - Pub O' Gold",
    "Slot Ranch Casino bar area",
    "Underground main tunnel",
    "Underground - Secret Lab",
    "Yucatan Casino upper platforms",
  ],
  "Whipped Cream": ["Palisades Mall's Central Grotto"],
  "Yellow Tall Chair": ["Near slot machines in Casinos"],
  "Zombie Mask": ["Stylin' Toddlers (Royal Flush Plaza 1st Floor)"],

  Sickle: ["Americana Casino - The American Historium"],
  Katana: ["Found after killing psychopaths in Case 4-1"],

  // === Case West 専用 ===
  "Impact Hammer": ["Research Laboratory (Case West)"],
  "Electric Prod": [
    "Fortune City Arena - Terror Togs (E101)",
    "Silver Strip - Hot Excitorama (N110)",
    "Slot Ranch Casino cashier and vault area",
    "Underground - Maintenance Room 31",
    "Uranus Zone central upper platforms",
    "Yucatan Casino - Maintenance Room 6",
  ],
  Defibrillator: ["Medical areas, hospital (Case West)"],
  "Medical Tray": ["Medical areas (Case West)"],
  "Syringe Gun": ["Research Laboratory (Case West)"],
  Chemicals: ["Research Laboratory (Case West)"],
  "Floor Buffer": ["Janitor areas (Case West)"],

  // === OTR 専用 ===
  "Boomerang": [
    "Food Court - Lombardi's (F104)",
    "Fortune City Arena main floor",
    "Palisades Mall - Maintenance Room 7/KokoNutz Sports Town (P110)/Under the Sea Travels (P207)",
    "Platinum Strip cinema rooftop",
    "Royal Flush Plaza - The Man's Sport (R103)",
    "Silver Strip - Barrel of Goods (N104)",
    "Tape It or Die Set",
  ],
  "Alien Head": [
    "Royal Flush Plaza - Ye Olde Toybox (R107)",
    "Slot Ranch Casino stage area",
    "Uranus Zone east souvenir kiosk / stage area",
    "Uranus Zone Maintenance Room 4 / Astonishing Illusions (U103)",
    "Yucatan Casino - Baron Von Brathaus (Y101)",
  ],
  "Tennis Ball Launcher": ["Uranus Zone (OTR)"],
  "Grass Trimmer": ["Fortune Park (OTR)"],
  "Escape Pod": ["Uranus Zone (OTR)"],
};

/** アイテムのWikiページURLを取得 */
export function getItemWikiUrl(itemName: string): string {
  const base = itemName.split(" or ")[0].trim();
  const encoded = encodeURIComponent(base + "_(Dead_Rising_2)");
  return `${WIKI_BASE}${encoded}`;
}

/** アイテムの取得場所を取得（部分一致で検索） */
export function getItemLocations(itemName: string): string[] {
  const normalized = itemName.trim();
  if (!normalized) return [];

  // 完全一致を優先
  if (ITEM_LOCATIONS[normalized]) {
    return ITEM_LOCATIONS[normalized];
  }

  // "LMG or Merc Assault Rifle" 等の複合名 → 最初の部分で検索
  const firstPart = normalized.split(" or ")[0].trim();
  if (ITEM_LOCATIONS[firstPart]) {
    return ITEM_LOCATIONS[firstPart];
  }

  // 部分一致
  for (const [key, locations] of Object.entries(ITEM_LOCATIONS)) {
    if (
      normalized.toLowerCase().includes(key.toLowerCase()) ||
      firstPart.toLowerCase().includes(key.toLowerCase())
    ) {
      return locations;
    }
  }

  return [];
}
